### ISSUE TITLE
error：sec_nodes and sec_edges

### ISSUE THREAD

**Issue by yichenstone** [fmannhardt/heuristicsmineR#6]
causal_net(
    threshold = 0.8,
    threshold_frequency = 0,
    type_nodes = causal_frequency("absolute"),
    type_edges = causal_frequency("relative"),
    sec_nodes = causal_performance(mean, "mins"),
    sec_edges = causal_performance(mean, "days")
    )

——————run result
error: Problem with `summarise()` column `label`.
i `label = do.call(...)`.
x `label` must be size 7 or 1, not 6.
i An earlier column had size 7.
i The error occurred in group 6: act = "1-1-6", from_id = 6.

Using a CSV file, which is converted to events through: _bupaR::activities_to_eventlog_, I don’t know how to resolve this error.

**Comment by fmannhardt** [comment]
I would need to have the data to be able to reproduce this.

**Comment by fmannhardt** [comment]
Impossible to reproduce.
