### ISSUE TITLE
Error in count_precedence with causal net 

### ISSUE THREAD

**Issue by larachammas** [fmannhardt/heuristicsmineR#8]
After generating event logs using bupaR I receive this error note when I try to generate a causal_net(). I did not receive this error yesterday but when rerunning all the code today I cannot seem to generate the precedence matrix anymore. What should I be doing differently? I am at a loss for what could be wrong

<img width="608" alt="Screenshot 2022-08-03 at 11 12 30" src="https://user-images.githubusercontent.com/50211164/182584070-0953d34c-e87a-4e15-9a77-8b777ce9c324.png">

**Comment by fmannhardt** [comment]
Try to upgrade to v0.2.7 there was a change in bupaR that was incompatible with the old heuristicsmineR version.

**Comment by fmannhardt** [comment]
Closing since this probably was a version conflict issue as written above.
